version: '3.9'

services:
  app:
    image: ghcr.io/odevchan-ps/repo01-app:latest
    container_name: laravel_app
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

  db:
    image: mysql:8.0
    platform: linux/amd64
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpass
      TZ: Asia/Tokyo
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout:  3s
      retries:  10
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro

  batch:
    image: ghcr.io/odevchan-ps/repo01-batch:latest
    container_name: python_batch
    restart: always
    env_file:
      - ./batch/.env
    depends_on:
      db:
        condition: service_healthy
    environment:
      TZ: Asia/Tokyo
    volumes:
      - /etc/localtime:/etc/localtime:ro

volumes:
  db_data:

