services:
  app:
    image: ghcr.io/odevchan-ps/repo01-app:latest
    container_name: laravel_app
    volumes:
      - ./:/var/www/html:cached
      - /var/www/html/vendor
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

  db:
    image: mariadb:10.5
    container_name: laravel_db
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=laravel_db
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravelpass
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-client.cnf:/etc/mysql/conf.d/mysql-client.cnf:ro

  batch:
    image: ghcr.io/odevchan-ps/repo01-batch:latest
    container_name: python_batch
    restart: always
    env_file:
      - ./batch/.env
    depends_on:
      - db
    environment:
      TZ: Asia/Tokyo
    volumes:
      - /etc/localtime:/etc/localtime:ro

volumes:
  db_data:
