# .github/workflows/debug-dpkg.yml
name: debug dpkg
on: workflow_dispatch

permissions:
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build batch image in plain mode
        run: |
          docker build --progress=plain --platform=linux/arm/v7 -f batch/Dockerfile batch